// Minimal, buildable Phaser shell for schema v2 custom-loop games.
// It intentionally contains no arcade player, falling hazards, coins, or scoring loop.
// LLM/game-specific implementation replaces GameScene while preserving the shared contracts.

export function buildCustomShellFiles(spec) {
  const files = new Map();
  const id = spec.game.id;
  const title = spec.game.title;
  const rulesJson = JSON.stringify(spec.rules, null, 2);

  files.set('package.json', JSON.stringify({
    name: id,
    version: '0.1.0',
    private: true,
    type: 'module',
    engines: { node: '>=18' },
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { phaser: '^3.90.0' },
    devDependencies: { vite: '^6.3.5' },
  }, null, 2) + '\n');

  files.set('index.html', `<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />\n  <title>${title}</title>\n</head>\n<body>\n  <main id="game" aria-label="${title}"></main>\n  <script type="module" src="/src/main.js"></script>\n</body>\n</html>\n`);
  files.set('src/style.css', `html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#050b09}body{display:grid;place-items:center}#game{width:100%;height:100%;display:grid;place-items:center}canvas{display:block;max-width:100%;max-height:100%}\n`);
  files.set('src/main.js', `import Phaser from 'phaser';\nimport './style.css';\nimport config from './game/config.js';\nimport{AudioManager}from'./game/systems/AudioManager.js';\nconst game = new Phaser.Game(config);\nif (typeof window !== 'undefined'){window.__GAME__=game;window.__GAME_QA__={getState:()=>window.__GAME_LAYOUT_BOUNDS__||null,audioState:()=>AudioManager.snapshot()};}\n`);
  files.set('src/game/data/game-spec.json', JSON.stringify(spec, null, 2) + '\n');
  files.set('src/game/data/spec.js', `import gameSpec from './game-spec.json';\nexport const SPEC = gameSpec;\nexport const SCENES = { BOOT:'Boot', LOADING:'Loading', HOME:'Home', GAME:'Game', PAUSE:'Pause', GAMEOVER:'GameOver' };\n`);
  files.set('src/game/config/customGameConfig.js', `import { SPEC } from '../data/spec.js';\nexport const CUSTOM_GAME_CONFIG = Object.freeze({ implementationStatus: SPEC.implementationStatus, rules: Object.freeze(${rulesJson}) });\n`);
  files.set('src/game/config.js', `import Phaser from 'phaser';\nimport { SPEC } from './data/spec.js';\nimport BootScene from './scenes/BootScene.js';\nimport LoadingScene from './scenes/LoadingScene.js';\nimport HomeScene from './scenes/HomeScene.js';\nimport GameScene from './scenes/GameScene.js';\nimport PauseScene from './scenes/PauseScene.js';\nimport GameOverScene from './scenes/GameOverScene.js';\nexport default { type:Phaser.AUTO, parent:'game', width:SPEC.canvas.width, height:SPEC.canvas.height, backgroundColor:SPEC.canvas.backgroundColor, scale:{ mode:SPEC.canvas.scaleMode==='cover'?Phaser.Scale.ENVELOP:Phaser.Scale.FIT, autoCenter:Phaser.Scale.CENTER_BOTH }, fps:{target:SPEC.performance.targetFps||60}, scene:[BootScene,LoadingScene,HomeScene,GameScene,PauseScene,GameOverScene] };\n`);

  files.set('src/game/systems/SaveData.js', `import { SPEC } from '../data/spec.js';\nconst KEY=SPEC.game.id+'_settings';\nexport const SaveData={getSettings(){try{return{mute:false,saveVersion:1,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{mute:false,saveVersion:1}}},setSettings(next){try{localStorage.setItem(KEY,JSON.stringify({...this.getSettings(),...next}))}catch{}}};\n`);
  files.set('src/game/systems/AudioManager.js', `let current=null;let muted=false;export const AudioManager={setMuted(value){muted=!!value;if(current)current.setMute?.(muted)},playMusic(scene,key){if(current?.key===key)return current;current?.stop?.();current=scene.sound?.add?.(key,{loop:true,volume:.6})||null;if(current){current.setMute?.(muted);current.play?.()}return current},pauseMusic(){current?.pause?.()},resumeMusic(){current?.resume?.()},stopMusic(){current?.stop?.();current=null},snapshot(){return{instances:current?1:0,key:current?.key||null,isPlaying:!!current?.isPlaying,isPaused:!!current?.isPaused,mute:muted}}};\n`);
  files.set('src/game/systems/LayoutRegistry.js', `export function publishLayout(scene,entries,options={}){const b=scene.scale?.canvasBounds,w=scene.cameras?.main?.worldView;if(!b||!w?.width||!w?.height)return;const sx=b.width/w.width,sy=b.height/w.height;const items=[];for(const e of entries){const o=e?.obj;if(!o||o.visible===false||typeof o.getBounds!=='function')continue;const r=o.getBounds();items.push({id:e.id,x:b.left+(r.x-w.x)*sx,y:b.top+(r.y-w.y)*sy,width:r.width*sx,height:r.height*sy,visible:true,allowOverlap:e.allowOverlap===true,allowOverlapWith:e.allowOverlapWith||[]})}if(typeof window!=='undefined')window.__GAME_LAYOUT_BOUNDS__={scene:scene.scene?.key||'',items,requiredIds:options.requiredIds||entries.map(e=>e.id)}}\nexport function clearLayout(){if(typeof window!=='undefined')window.__GAME_LAYOUT_BOUNDS__={scene:'',items:[],requiredIds:[]}}\n`);
  files.set('src/game/ui/MobileButton.js', `export function makeTextButton(scene,x,y,label,onClick,{width=220,height=60,oneShot=false,fireOn='pointerup',disabled=false}={}){const bg=scene.add.rectangle(x,y,width,height,0x22b357,1).setStrokeStyle(2,0xffffff,.9);const txt=scene.add.text(x,y,label,{fontFamily:'Arial Black,Arial',fontSize:'22px',color:'#fff',stroke:'#000',strokeThickness:4}).setOrigin(.5);let fired=false,enabled=!disabled;const resetVisual=()=>{bg.setScale(1);txt.setScale(1)};const fire=()=>{if(!enabled||fired)return;if(oneShot){fired=true;bg.disableInteractive()}onClick?.()};const setEnabled=(value)=>{enabled=!!value;if(enabled&&!fired)bg.setInteractive({useHandCursor:true});else bg.disableInteractive();resetVisual()};setEnabled(enabled);bg.on('pointerdown',()=>{if(!enabled||fired)return;bg.setScale(.96);txt.setScale(.96);if(fireOn==='pointerdown')fire()});bg.on('pointerup',()=>{if(!enabled||fired)return;resetVisual();if(fireOn!=='pointerdown')fire()});bg.on('pointerout',resetVisual);return{bg,txt,resetVisual,setEnabled,destroy(){bg.destroy();txt.destroy()}}}\n`);

  files.set('src/game/scenes/BootScene.js', `import Phaser from 'phaser';import{SCENES}from'../data/spec.js';import{SaveData}from'../systems/SaveData.js';export default class BootScene extends Phaser.Scene{constructor(){super(SCENES.BOOT)}create(){SaveData.getSettings();this.scene.start(SCENES.LOADING)}}\n`);
  files.set('src/game/scenes/LoadingScene.js', `import Phaser from'phaser';import{SCENES,SPEC}from'../data/spec.js';import{publishLayout}from'../systems/LayoutRegistry.js';export default class LoadingScene extends Phaser.Scene{constructor(){super(SCENES.LOADING)}create(){const{width,height}=SPEC.canvas;this.title=this.add.text(width/2,height*.42,SPEC.game.title,{fontFamily:'Arial Black,Arial',fontSize:'32px',color:'#fff',align:'center'}).setOrigin(.5);this.status=this.add.text(width/2,height*.52,'Loading custom game shell…',{fontFamily:'Arial',fontSize:'16px',color:'#b9d7ff'}).setOrigin(.5);publishLayout(this,[{id:'loading-title',obj:this.title},{id:'loading-status',obj:this.status}],{requiredIds:['loading-title','loading-status']});this.time.delayedCall(120,()=>this.scene.start(SCENES.HOME))}}\n`);
  files.set('src/game/scenes/HomeScene.js', `import Phaser from'phaser';import{SCENES,SPEC}from'../data/spec.js';import{makeTextButton}from'../ui/MobileButton.js';import{publishLayout}from'../systems/LayoutRegistry.js';export default class HomeScene extends Phaser.Scene{constructor(){super(SCENES.HOME)}create(){const{width,height}=SPEC.canvas;this.title=this.add.text(width/2,height*.22,SPEC.game.title,{fontFamily:'Arial Black,Arial',fontSize:'34px',color:'#fff',align:'center',wordWrap:{width:width-40}}).setOrigin(.5);this.goal=this.add.text(width/2,height*.42,'Goal: '+SPEC.rules.goal+'\\nProgress: '+SPEC.rules.progressMetric,{fontFamily:'Arial',fontSize:'18px',color:'#b8f0dc',align:'center',wordWrap:{width:width-50}}).setOrigin(.5);this.play=makeTextButton(this,width/2,height*.7,'PLAY',()=>this.scene.start(SCENES.GAME),{oneShot:true});publishLayout(this,[{id:'home-title',obj:this.title},{id:'home-goal',obj:this.goal},{id:'play',obj:this.play.bg}],{requiredIds:['home-title','home-goal','play']})}}\n`);
  files.set('src/game/scenes/GameScene.js', `import Phaser from'phaser';import{SCENES,SPEC}from'../data/spec.js';import{makeTextButton}from'../ui/MobileButton.js';import{publishLayout,clearLayout}from'../systems/LayoutRegistry.js';export default class GameScene extends Phaser.Scene{constructor(){super(SCENES.GAME)}create(){const{width,height}=SPEC.canvas;this.title=this.add.text(width/2,90,'CUSTOM LOOP IMPLEMENTATION REQUIRED',{fontFamily:'Arial Black,Arial',fontSize:'20px',color:'#ffd578',align:'center',wordWrap:{width:width-30}}).setOrigin(.5);this.progress=this.add.text(width/2,height*.45,'Implement the genre-defining systems, then set implementationStatus to production-demo.',{fontFamily:'Arial',fontSize:'17px',color:'#fff',align:'center',wordWrap:{width:width-50}}).setOrigin(.5);this.pause=makeTextButton(this,width-55,45,'Ⅱ',()=>{this.scene.launch(SCENES.PAUSE);this.scene.pause()},{width:52,height:46,oneShot:true});this.publish=()=>publishLayout(this,[{id:'game-status',obj:this.title},{id:'progress-metric',obj:this.progress},{id:'pause',obj:this.pause.bg}],{requiredIds:['game-status','progress-metric','pause']});this.publish();this.events.once(Phaser.Scenes.Events.SHUTDOWN,clearLayout)}}\n`);
  files.set('src/game/scenes/PauseScene.js', `import Phaser from'phaser';import{SCENES,SPEC}from'../data/spec.js';import{makeTextButton}from'../ui/MobileButton.js';import{publishLayout}from'../systems/LayoutRegistry.js';export default class PauseScene extends Phaser.Scene{constructor(){super(SCENES.PAUSE)}create(){const{width,height}=SPEC.canvas;this.add.rectangle(0,0,width,height,0x000000,.72).setOrigin(0);this.title=this.add.text(width/2,height*.32,'PAUSED',{fontFamily:'Arial Black,Arial',fontSize:'40px',color:'#fff'}).setOrigin(.5);this.resume=makeTextButton(this,width/2,height*.5,'RESUME',()=>{this.scene.stop();this.scene.resume(SCENES.GAME)},{oneShot:true});this.home=makeTextButton(this,width/2,height*.62,'HOME',()=>{this.scene.stop(SCENES.GAME);this.scene.start(SCENES.HOME)},{oneShot:true});publishLayout(this,[{id:'pause-title',obj:this.title},{id:'resume',obj:this.resume.bg},{id:'home',obj:this.home.bg}],{requiredIds:['pause-title','resume','home']})}}\n`);
  files.set('src/game/scenes/GameOverScene.js', `import Phaser from'phaser';import{SCENES,SPEC}from'../data/spec.js';import{makeTextButton}from'../ui/MobileButton.js';import{publishLayout}from'../systems/LayoutRegistry.js';export default class GameOverScene extends Phaser.Scene{constructor(){super(SCENES.GAMEOVER)}create(data={}){const{width,height}=SPEC.canvas;this.title=this.add.text(width/2,height*.25,data.outcome==='win'?'SUCCESS':'FAILED',{fontFamily:'Arial Black,Arial',fontSize:'40px',color:'#fff'}).setOrigin(.5);this.retry=makeTextButton(this,width/2,height*.62,'RETRY',()=>this.scene.start(SCENES.GAME),{oneShot:true});this.home=makeTextButton(this,width/2,height*.74,'HOME',()=>this.scene.start(SCENES.HOME),{oneShot:true});publishLayout(this,[{id:'result-title',obj:this.title},{id:'retry',obj:this.retry.bg},{id:'home',obj:this.home.bg}],{requiredIds:['result-title','retry','home']})}}\n`);

  files.set('qa/capture-matrix.json', JSON.stringify({ schemaVersion:'1.0.0', viewports:[{width:390,height:844,dpr:2},{width:430,height:932,dpr:2},{width:1080,height:1920,dpr:1}], states:[{id:'loading',expectedScene:'Loading',requiredIds:['loading-title','loading-status']},{id:'home',expectedScene:'Home',requiredIds:['home-title','home-goal','play']},{id:'game',expectedScene:'Game',requiredIds:['game-status','progress-metric','pause']},{id:'pause',expectedScene:'Pause',requiredIds:['pause-title','resume','home']},{id:'result-win',expectedScene:'GameOver',requiredIds:['result-title','retry','home'],terminal:'win'},{id:'result-loss',expectedScene:'GameOver',requiredIds:['result-title','retry','home'],terminal:'loss'}] }, null, 2) + '\n');
  files.set('.dev-game-generated.json', JSON.stringify({ generator:'dev_game', schemaVersion:'2.0.0', gameId:id, template:'custom-shell' }, null, 2) + '\n');
  files.set('README.md', `# ${title}\n\nCustom-loop Foundation generated by dev_game. This shell is intentionally not a completed game. Implement the genre-defining loop, wire assets/audio/QA adapters, then change implementationStatus only after the full production gate passes.\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm run dev\nnpm run build\n\`\`\`\n`);
  return { files, withSfx: false };
}
